/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package semester.project;

import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import static semester.project.pathforimage.backgroundpath;

/**
 *
 * @author Desktop
 */
public class DashboardPage extends javax.swing.JFrame {

    /**
     * Creates new form DashboardPage
     */
    public DashboardPage() {
        setSize(850, 769);
         setResizable(false);
        setTitle("Cookin' RN");
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ImageIcon imageIcon = new ImageIcon(backgroundpath);
        Image image = imageIcon.getImage();
        dashboardPanel = new ImagePanel(image);
        menuButton = new javax.swing.JButton();
        waitlistButton = new javax.swing.JButton();
        timingsButton = new javax.swing.JButton();
        reservationButton = new javax.swing.JButton();
        logoutButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        dashboardPanel.setMaximumSize(new java.awt.Dimension(850, 769));
        dashboardPanel.setMinimumSize(new java.awt.Dimension(850, 769));
        dashboardPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        menuButton.setBackground(new java.awt.Color(12, 191, 222));
        menuButton.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        menuButton.setForeground(new java.awt.Color(255, 255, 255));
        menuButton.setText("Menu");
        menuButton.setBorderPainted(false);
        menuButton.setFocusPainted(false);
        menuButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuButtonActionPerformed(evt);
            }
        });
        dashboardPanel.add(menuButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 520, 250, 69));
        menuButton.requestFocus();

        waitlistButton.setBackground(new java.awt.Color(12, 191, 222));
        waitlistButton.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        waitlistButton.setForeground(new java.awt.Color(255, 255, 255));
        waitlistButton.setText("Waitlist");
        waitlistButton.setBorderPainted(false);
        waitlistButton.setFocusPainted(false);
        waitlistButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                waitlistButtonActionPerformed(evt);
            }
        });
        dashboardPanel.add(waitlistButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 600, 250, 69));
        menuButton.requestFocus();

        timingsButton.setBackground(new java.awt.Color(12, 191, 222));
        timingsButton.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        timingsButton.setForeground(new java.awt.Color(255, 255, 255));
        timingsButton.setText("Timings");
        timingsButton.setBorderPainted(false);
        timingsButton.setFocusPainted(false);
        timingsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                timingsButtonActionPerformed(evt);
            }
        });
        dashboardPanel.add(timingsButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 520, 250, 69));
        menuButton.requestFocus();

        reservationButton.setBackground(new java.awt.Color(12, 191, 222));
        reservationButton.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        reservationButton.setForeground(new java.awt.Color(255, 255, 255));
        reservationButton.setText("Reservations");
        reservationButton.setBorderPainted(false);
        reservationButton.setFocusPainted(false);
        reservationButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reservationButtonActionPerformed(evt);
            }
        });
        dashboardPanel.add(reservationButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 520, 250, 150));
        menuButton.requestFocus();

        logoutButton.setBackground(new java.awt.Color(12, 191, 222));
        logoutButton.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        logoutButton.setForeground(new java.awt.Color(255, 255, 255));
        logoutButton.setText("Log Out");
        logoutButton.setBorderPainted(false);
        logoutButton.setFocusPainted(false);
        logoutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutButtonActionPerformed(evt);
            }
        });
        dashboardPanel.add(logoutButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 600, 250, 69));
        menuButton.requestFocus();

        getContentPane().add(dashboardPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 850, 769));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuButtonActionPerformed
        // TODO add your handling code here:
        MenuPage newFrame = new MenuPage();
        newFrame.setVisible(true);
        dispose();
    }//GEN-LAST:event_menuButtonActionPerformed

    private void timingsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_timingsButtonActionPerformed
        // TODO add your handling code here:
        TimingsPage newFrame = new TimingsPage();
        newFrame.setVisible(true);
        dispose();
    }//GEN-LAST:event_timingsButtonActionPerformed

    private void reservationButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reservationButtonActionPerformed
        // TODO add your handling code here:
        ReservationsPage newFrame = new ReservationsPage();
        newFrame.setVisible(true);
        dispose();
    }//GEN-LAST:event_reservationButtonActionPerformed

    private void waitlistButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_waitlistButtonActionPerformed
        // TODO add your handling code here:
        WaitlistPage newFrame = new WaitlistPage();
        newFrame.setVisible(true);
        dispose();
    }//GEN-LAST:event_waitlistButtonActionPerformed

    private void logoutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutButtonActionPerformed
        // TODO add your handling code here:
        LoginPage newFrame = new LoginPage();
        newFrame.setVisible(true);
        dispose();
    }//GEN-LAST:event_logoutButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DashboardPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DashboardPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DashboardPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DashboardPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DashboardPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel dashboardPanel;
    private javax.swing.JButton logoutButton;
    private javax.swing.JButton menuButton;
    private javax.swing.JButton reservationButton;
    private javax.swing.JButton timingsButton;
    private javax.swing.JButton waitlistButton;
    // End of variables declaration//GEN-END:variables
}
