/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package semester.project;

import java.awt.Color;
import java.awt.Image;
import java.awt.event.FocusAdapter;
import java.awt.event.FocusEvent;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import static semester.project.pathforimage.backgroundpath;
import static semester.project.pathforimage.usernameCurrentUser;
import static semester.project.SaveAccountData.SaveReservation;

/**
 *
 * @author Desktop
 */
public class NewReservationPage extends javax.swing.JFrame {
    int index = 0;
    
    public void changeIndex(int index1)
    {
        index = index1;
    }
    /**
     * Creates new form NewReservationPage
     */
    public NewReservationPage() {
        setSize(850, 769);
        setResizable(false);
        setTitle("Cookin' RN");
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);

        initComponents();
        
        jComboBox1.setSelectedIndex(index);
        /* Create and display the form */
        /*java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewReservationPage().setVisible(true);
            }
        });*/
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ImageIcon imageIcon = new ImageIcon(backgroundpath);
        Image image = imageIcon.getImage();
        jPanel1 = new ImagePanel(image);
        capacityText1 = new javax.swing.JTextField();
        reservationPlaceButton = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        backButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(850, 769));
        setMinimumSize(new java.awt.Dimension(850, 769));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setMaximumSize(new java.awt.Dimension(850, 769));
        jPanel1.setMinimumSize(new java.awt.Dimension(850, 769));
        jPanel1.setPreferredSize(new java.awt.Dimension(850, 769));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        capacityText1.setBorder(null);
        capacityText1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                capacityText1ActionPerformed(evt);
            }
        });
        capacityText1.setText("Capacity");
        jPanel1.add(capacityText1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 410, 250, 50));
        capacityText1.addFocusListener(new FocusAdapter() {
            @Override
            public void focusGained(FocusEvent e) {
                if (capacityText1.getText().equals("Capacity")) {
                    capacityText1.setText("");
                    capacityText1.setForeground(Color.BLACK);
                }
            }

            @Override
            public void focusLost(FocusEvent e) {
                if (capacityText1.getText().isEmpty()) {
                    capacityText1.setText("Capacity");
                    capacityText1.setForeground(Color.GRAY);
                }
            }
        });

        reservationPlaceButton.setBackground(new java.awt.Color(12, 191, 222));
        reservationPlaceButton.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        reservationPlaceButton.setForeground(new java.awt.Color(255, 255, 255));
        reservationPlaceButton.setText("Place Reservation");
        reservationPlaceButton.setBorderPainted(false);
        reservationPlaceButton.setFocusPainted(false);
        reservationPlaceButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reservationPlaceButtonActionPerformed(evt);
            }
        });
        jPanel1.add(reservationPlaceButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 470, 250, 70));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Table 1", "Table 2", "Table 3", "Table 4", "Take 5", "Table 6" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 350, 250, 50));

        backButton1.setBackground(new java.awt.Color(12, 191, 222));
        backButton1.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        backButton1.setForeground(new java.awt.Color(255, 255, 255));
        backButton1.setText("Back");
        backButton1.setBorderPainted(false);
        backButton1.setFocusPainted(false);
        backButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(backButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 550, 160, 50));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void capacityText1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_capacityText1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_capacityText1ActionPerformed

    private void reservationPlaceButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reservationPlaceButtonActionPerformed
        // TODO add your handling code here:
       
       
    DateTimeFormatter dtf = DateTimeFormatter.ofPattern("yyyy/MM/dd HH:mm:ss");
    LocalDateTime now = LocalDateTime.now();
    
    String capacity = capacityText1.getText();
    int reservationNumber = 1;
    String values = reservationNumber + ",'" + now +  "', " + capacity + ", '" + usernameCurrentUser + "'";
    
       SaveReservation(values);
       
        DashboardPage newFrame = new DashboardPage();
        newFrame.setVisible(true);
        dispose();
    }//GEN-LAST:event_reservationPlaceButtonActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void backButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_backButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewReservationPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewReservationPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewReservationPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewReservationPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backButton1;
    private javax.swing.JTextField capacityText1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton reservationPlaceButton;
    // End of variables declaration//GEN-END:variables
}
