
package semester.project;

import java.awt.Image;
import java.awt.PopupMenu;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import static semester.project.pathforimage.backgroundpath;

/**
 *
 * @author Desktop
 */
public class PlaceReservationPage extends javax.swing.JFrame {

    public PlaceReservationPage() {
        
        setSize(850, 769);
         setResizable(false);
        setTitle("Cookin' RN");
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
       
        initComponents();

        setLocationRelativeTo(null); // Center the frame on the screens
        
    }

    public static void main(String[] args) {
    java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PlaceReservationPage().setVisible(true);
            }
        });
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ImageIcon imageIcon = new ImageIcon(backgroundpath);
        Image image = imageIcon.getImage();
        javax.swing.JPanel jPanel1 = new ImagePanel(image);
        Table1 = new javax.swing.JButton();
        Table2 = new javax.swing.JButton();
        Table3 = new javax.swing.JButton();
        Table4 = new javax.swing.JButton();
        Table5 = new javax.swing.JButton();
        Table6 = new javax.swing.JButton();
        Back = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Cookin' RN");
        setIconImages(null);
        setMinimumSize(new java.awt.Dimension(850, 769));

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Table1.setBackground(new java.awt.Color(12, 191, 222));
        Table1.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        Table1.setForeground(new java.awt.Color(255, 255, 255));
        Table1.setText("Table1");
        Table1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Table1ActionPerformed(evt);
            }
        });
        jPanel1.add(Table1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 350, 140, 69));
        jButton1.setFocusPainted(false);

        Table2.setBackground(new java.awt.Color(12, 191, 222));
        Table2.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        Table2.setForeground(new java.awt.Color(255, 255, 255));
        Table2.setText("Table2");
        Table2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Table2ActionPerformed(evt);
            }
        });
        jPanel1.add(Table2, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 350, 140, 69));
        jButton1.setFocusPainted(false);

        Table3.setBackground(new java.awt.Color(12, 191, 222));
        Table3.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        Table3.setForeground(new java.awt.Color(255, 255, 255));
        Table3.setText("Table3");
        Table3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Table3ActionPerformed(evt);
            }
        });
        jPanel1.add(Table3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 510, 140, 69));
        jButton1.setFocusPainted(false);

        Table4.setBackground(new java.awt.Color(12, 191, 222));
        Table4.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        Table4.setForeground(new java.awt.Color(255, 255, 255));
        Table4.setText("Table4");
        Table4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Table4ActionPerformed(evt);
            }
        });
        jPanel1.add(Table4, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 510, 140, 69));
        jButton1.setFocusPainted(false);

        Table5.setBackground(new java.awt.Color(12, 191, 222));
        Table5.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        Table5.setForeground(new java.awt.Color(255, 255, 255));
        Table5.setText("Table5");
        Table5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Table5ActionPerformed(evt);
            }
        });
        jPanel1.add(Table5, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 350, 140, 69));
        jButton1.setFocusPainted(false);

        Table6.setBackground(new java.awt.Color(12, 191, 222));
        Table6.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        Table6.setForeground(new java.awt.Color(255, 255, 255));
        Table6.setText("Table6");
        Table6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Table6ActionPerformed(evt);
            }
        });
        jPanel1.add(Table6, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 510, 140, 69));
        jButton1.setFocusPainted(false);

        Back.setBackground(new java.awt.Color(12, 191, 222));
        Back.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        Back.setForeground(new java.awt.Color(255, 255, 255));
        Back.setText("Back");
        Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackActionPerformed(evt);
            }
        });
        jPanel1.add(Back, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 680, 150, 40));
        jButton1.setFocusPainted(false);

        jButton1.setBackground(new java.awt.Color(12, 191, 222));
        jButton1.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setEnabled(false);
        jButton1.setFocusPainted(false);
        jButton1.setFocusable(false);
        jButton1.setRequestFocusEnabled(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, 10, 350));
        jButton1.setFocusPainted(false);

        jButton10.setBackground(new java.awt.Color(12, 191, 222));
        jButton10.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        jButton10.setForeground(new java.awt.Color(255, 255, 255));
        jButton10.setEnabled(false);
        jButton10.setFocusPainted(false);
        jButton10.setFocusable(false);
        jButton10.setRequestFocusEnabled(false);
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, 800, 10));
        jButton1.setFocusPainted(false);

        jButton11.setBackground(new java.awt.Color(12, 191, 222));
        jButton11.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        jButton11.setForeground(new java.awt.Color(255, 255, 255));
        jButton11.setEnabled(false);
        jButton11.setFocusPainted(false);
        jButton11.setFocusable(false);
        jButton11.setRequestFocusEnabled(false);
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 630, 800, 10));
        jButton1.setFocusPainted(false);

        jButton12.setBackground(new java.awt.Color(12, 191, 222));
        jButton12.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        jButton12.setForeground(new java.awt.Color(255, 255, 255));
        jButton12.setEnabled(false);
        jButton12.setFocusPainted(false);
        jButton12.setFocusable(false);
        jButton12.setRequestFocusEnabled(false);
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton12, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 290, 10, 260));
        jButton1.setFocusPainted(false);

        jButton13.setBackground(new java.awt.Color(12, 191, 222));
        jButton13.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        jButton13.setForeground(new java.awt.Color(255, 255, 255));
        jButton13.setEnabled(false);
        jButton13.setFocusPainted(false);
        jButton13.setFocusable(false);
        jButton13.setRequestFocusEnabled(false);
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton13, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 290, 10, 350));
        jButton1.setFocusPainted(false);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);
        // Add the image panel to the frame

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
                LoginPage newFrame = new LoginPage();
                newFrame.setVisible(true);
                dispose(); 
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void Table1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Table1ActionPerformed
        // TODO add your handling code here:
        NewReservationPage newFrame = new NewReservationPage();
        newFrame.changeIndex(0);
        newFrame.setVisible(true);
        dispose();
    }//GEN-LAST:event_Table1ActionPerformed

    private void Table3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Table3ActionPerformed
        // TODO add your handling code here:
        NewReservationPage newFrame = new NewReservationPage();
        newFrame.changeIndex(2);
        newFrame.setVisible(true);
        dispose();
    }//GEN-LAST:event_Table3ActionPerformed

    private void Table6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Table6ActionPerformed
        // TODO add your handling code here:
        NewReservationPage newFrame = new NewReservationPage();
        newFrame.changeIndex(5);
        newFrame.setVisible(true);
        dispose();
    }//GEN-LAST:event_Table6ActionPerformed

    private void Table2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Table2ActionPerformed
        // TODO add your handling code here:
        NewReservationPage newFrame = new NewReservationPage();
        newFrame.changeIndex(1);
        newFrame.setVisible(true);
        dispose();
    }//GEN-LAST:event_Table2ActionPerformed

    private void BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackActionPerformed
        // TODO add your handling code here:
        ReservationsPage newFrame = new ReservationsPage();
        newFrame.setVisible(true);
        dispose();
    }//GEN-LAST:event_BackActionPerformed

    private void Table4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Table4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Table4ActionPerformed

    private void Table5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Table5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Table5ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton12ActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton13ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Back;
    private javax.swing.JButton Table1;
    private javax.swing.JButton Table2;
    private javax.swing.JButton Table3;
    private javax.swing.JButton Table4;
    private javax.swing.JButton Table5;
    private javax.swing.JButton Table6;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    // End of variables declaration//GEN-END:variables
}
