/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package semester.project;

import java.awt.Image;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import static semester.project.SaveAccountData.loadReservation;
import static semester.project.pathforimage.backgroundpath;

/**
 *
 * @author Desktop
 */
public class ViewReservationPage extends javax.swing.JFrame {

    /**
     * Creates new form ViewReservation
     */
    public ViewReservationPage() throws Exception {
        setSize(850, 769);
        setResizable(false);
        setTitle("Cookin' RN");
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);

        
        initComponents();
        String data = "";
        
        try {
        data = loadReservation(1);
        }
        catch (Exception ex) {
            
        }
        
        String array[] = data.split(",");
        
        resNumberLabel.setText("Reservation Number: " + array[0]);
        dateLabel.setText("Date & Time: " + array[1]);
        capacityLabel.setText("Capacity: " + array[2]);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ImageIcon imageIcon = new ImageIcon(backgroundpath);
        Image image = imageIcon.getImage();
        javax.swing.JPanel viewReservationPanel = new ImagePanel(image);
        backButton = new javax.swing.JButton();
        capacityLabel = new javax.swing.JLabel();
        resNumberLabel = new javax.swing.JLabel();
        dateLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(850, 769));
        setMinimumSize(new java.awt.Dimension(850, 769));

        viewReservationPanel.setMaximumSize(new java.awt.Dimension(850, 769));
        viewReservationPanel.setMinimumSize(new java.awt.Dimension(850, 769));
        viewReservationPanel.setPreferredSize(new java.awt.Dimension(850, 769));
        viewReservationPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        backButton.setBackground(new java.awt.Color(12, 191, 222));
        backButton.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        backButton.setForeground(new java.awt.Color(255, 255, 255));
        backButton.setText("Back");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });
        viewReservationPanel.add(backButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 560, 243, 69));
        backButton.setFocusPainted(false);

        capacityLabel.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        capacityLabel.setForeground(new java.awt.Color(12, 191, 222));
        capacityLabel.setText("Capacity:");
        viewReservationPanel.add(capacityLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 460, 730, 50));

        resNumberLabel.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        resNumberLabel.setForeground(new java.awt.Color(12, 191, 222));
        resNumberLabel.setText("Reservation Number:");
        viewReservationPanel.add(resNumberLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 360, 760, 50));

        dateLabel.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        dateLabel.setForeground(new java.awt.Color(12, 191, 222));
        dateLabel.setText("Date & Time:");
        viewReservationPanel.add(dateLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 410, 750, 50));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(viewReservationPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(viewReservationPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 769, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        // Add the image panel to the frame

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        // TODO add your handling code here:
        ReservationsPage newFrame = new ReservationsPage();
        newFrame.setVisible(true);
        dispose();
    }//GEN-LAST:event_backButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewReservationPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewReservationPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewReservationPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewReservationPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new ViewReservationPage().setVisible(true);
                } catch (Exception ex) {
                    Logger.getLogger(ViewReservationPage.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backButton;
    private javax.swing.JLabel capacityLabel;
    private javax.swing.JLabel dateLabel;
    private javax.swing.JLabel resNumberLabel;
    // End of variables declaration//GEN-END:variables
}
