/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package semester.project;

import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import static semester.project.pathforimage.backgroundpath;

public class WaitlistPage extends javax.swing.JFrame {

    /**
     * Creates new form WaitlistPage
     */
    public WaitlistPage() {
        setSize(850, 769);
         setResizable(false);
        setTitle("Cookin' RN");
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ImageIcon imageIcon = new ImageIcon(backgroundpath);
        Image image = imageIcon.getImage();
        WaitlistPanel = new ImagePanel(image);
        estimatedQueueText = new javax.swing.JLabel();
        estimatedQueueTime = new javax.swing.JLabel();
        queuePeopleText = new javax.swing.JLabel();
        numberQueueText = new javax.swing.JLabel();
        menuButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(850, 769));
        setMinimumSize(new java.awt.Dimension(850, 769));
        setPreferredSize(new java.awt.Dimension(850, 769));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        WaitlistPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        estimatedQueueText.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        estimatedQueueText.setForeground(new java.awt.Color(12, 191, 222));
        estimatedQueueText.setText("Estimated Queue Time:");
        WaitlistPanel.add(estimatedQueueText, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 500, -1, 50));

        estimatedQueueTime.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        estimatedQueueTime.setForeground(new java.awt.Color(12, 191, 222));
        estimatedQueueTime.setText("~25 minutes or less");
        WaitlistPanel.add(estimatedQueueTime, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 500, 360, 50));

        queuePeopleText.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        queuePeopleText.setForeground(new java.awt.Color(12, 191, 222));
        queuePeopleText.setText("People in Queue:");
        WaitlistPanel.add(queuePeopleText, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 400, 290, 50));

        numberQueueText.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        numberQueueText.setForeground(new java.awt.Color(12, 191, 222));
        numberQueueText.setText("3 reservations");
        WaitlistPanel.add(numberQueueText, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 400, 240, 50));

        menuButton.setBackground(new java.awt.Color(12, 191, 222));
        menuButton.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        menuButton.setForeground(new java.awt.Color(255, 255, 255));
        menuButton.setText("Back");
        menuButton.setBorderPainted(false);
        menuButton.setFocusPainted(false);
        menuButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuButtonActionPerformed(evt);
            }
        });
        WaitlistPanel.add(menuButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 630, 250, 69));
        menuButton.requestFocus();

        getContentPane().add(WaitlistPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 850, 770));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuButtonActionPerformed
        // TODO add your handling code here:
        DashboardPage newFrame = new DashboardPage();
        newFrame.setVisible(true);
        dispose();
    }//GEN-LAST:event_menuButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(WaitlistPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(WaitlistPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(WaitlistPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(WaitlistPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new WaitlistPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel WaitlistPanel;
    private javax.swing.JLabel estimatedQueueText;
    private javax.swing.JLabel estimatedQueueTime;
    private javax.swing.JButton menuButton;
    private javax.swing.JLabel numberQueueText;
    private javax.swing.JLabel queuePeopleText;
    // End of variables declaration//GEN-END:variables
}
